blueprint:
  name: Sonoff TX Ultimate Ambient Light
  description: |
    Turns ambient light on if all channels are off & turns ambient light off as soon as one channel is on.
    Ambient light will automatically switch on at specified start time if all channels are off & will automatically switch off at specified end time.
    __Note:__ For multi-channel switches, a helper group will need to be created for the "TXSwitch" input.

    <a href="https://www.example.com">View more info on Blueprint Exchange</a>

  domain: automation
  author: Shaylen-TRD
  source_url: https://github.com/Shaylen-Trd/ha-blueprints/blob/main/SonoffTXambientLight/sonoffTXambientLight.yaml
  #Define inputs
  input:
    trigger_start_time:
      name: Start Time
      description: Time ambient light will turn on.
      selector:
        time:

    trigger_end_time:
      name: End Time
      description: Time ambient light will turn off.
      selector:
        time:

    trigger_tx_light:
      name: TxSwitch
      description: |
        The switch linked to the ambient light.
        __Note:__ Use a helper group for multi-channel switches
      selector:
        entity:
          filter:
            domain:
              - switch
              - light

    target_tx_ambient_light:
      name: TxAmbientLight
      description: The ambient light which will turn on/off.
      selector:
        #target:
        entity:
          filter:
            domain: light

mode: restart

#AUTOMATION
alias: Light blueprint
description: ""
#Trigger
triggers:
  - trigger: time
    at: !input trigger_start_time
    enabled: true
    id: start_time_trigger
  - trigger: time
    at: !input trigger_end_time
    enabled: true
    id: end_time_trigger
  - trigger: state
    entity_id:
      - !input trigger_tx_light
    id: switch_changed_trigger
conditions:
  - condition: or
    conditions:
      - condition: time
        after: !input trigger_start_time
        before: !input trigger_end_time
      - condition: trigger
        id:
          - start_time_trigger
          - end_time_trigger
#Actions
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - start_time_trigger
          - condition: state
            entity_id: !input trigger_tx_light
            state: "off"
        sequence:
          - action: light.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: !input target_tx_ambient_light
        alias: Start Ambient Light
      - conditions:
          - condition: trigger
            id:
              - end_time_trigger
        sequence:
          - action: light.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: !input target_tx_ambient_light
        alias: End Ambient Light
      - conditions:
          - condition: trigger
            id:
              - switch_changed_trigger
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input trigger_tx_light
                    state: "off"
                sequence:
                  - action: light.turn_on
                    metadata: {}
                    data: {}
                    target:
                      entity_id: !input target_tx_ambient_light
              - conditions:
                  - condition: state
                    entity_id: !input trigger_tx_light
                    state: "on"
                sequence:
                  - action: light.turn_off
                    metadata: {}
                    data: {}
                    target:
                      entity_id: !input target_tx_ambient_light
        alias: Start/End Ambient Light
